name: SSL
on: [push]
jobs:
  SSL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 
        with:
          persist-credentials: false
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          Version: 10

      - name: Install and Build ğŸ”§ 
        run: |
          chmod +x ./checker.sh
          ./checker.sh xhemj.js.org mingyan.js.org xhemj.eu.org www.xhemj.eu.org
          cp -rf ./output/ct.json ./public/ct.json
        env:
          CI: false
          

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: .
